# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc6e6960a55b01212ece10a5b92ba6fd14a8f4c0273223b6ebfc6cbcabe3bb2446cf914d5a0244bef1a95fadc315a0fb75c9c3255bb31c279d412b6e35803f6

test:
  secret_key_base: c5c5266aad5e9e98bfdd4a89744512dda70ecccd8fc1f06a7536200dce10ad085135818bc9f96d5e422b9fa4b0136d4e3efcdeb76855c13479d24550f7e12cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
